FROM node:26-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev --silent

FROM node:26-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .
RUN npm run build

FROM node:26-alpine
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY package*.json ./
ENV PORT=8000
EXPOSE 8000
CMD ["npm", "run", "start"]