events {}

http {
    upstream client {
        server client:5173;
    }

    upstream server {
        server server:8000;
    }

    server {
        listen 80;


        location /health {
            proxy_pass http://server;
        }

        location /api/ {
            proxy_pass http://server;
        }

        location /web/ {
            proxy_pass http://server;

            #socket setup
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location / {
            proxy_pass http://client;

            #socket setup for dev access
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}